name: find_any_movie
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  smooth_page_indicator: ^1.0.0+2
  webview_flutter: ^3.0.1
  cupertino_icons: ^1.0.3
  cached_network_image: ^3.1.0
  flutter_slidable: ^1.2.0
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.13
  json_annotation: ^4.4.0

  chopper: ^4.0.5
  logging: ^1.0.1
  provider: ^6.0.1
  equatable: ^2.0.3
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.3
  synchronized: ^3.0.0
  sqlbrite: ^2.1.0
  drift: ^1.4.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  chopper_generator: ^4.0.5
  drift_dev: ^1.4.0

  flutter_lints: ^1.0.4

flutter:
  assets:
    - assets/slider_images/last_duel.jpg
    - assets/slider_images/spider_man.jpg
    - assets/slider_images/saints.jpg
    - assets/slider_images/bond.jpg
    - assets/slider_images/crown.jpg
    - assets/slider_images/blank.png
    - assets/


  uses-material-design: true


